server:
  port: 901

spring:
  datasource:
    url: jdbc:mysql://192.168.203.101:3306/web-admin?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: chennewtoo_
    username: root
